const state={view:'dashboard',filter:'all',query:'',packs:[{id:'P-26-001',material:'Magnesium bisglycinate',lot:'23',exp:'01/28',box:'B-23',position:'4RL',status:'OTEVŘENÝ'},{id:'P-26-002',material:'Magnesium bisglycinate',lot:'45',exp:'02/28',box:'B-23',position:'4RL',status:'NOVÝ'},{id:'P-26-003',material:'Vitamin C',lot:'75',exp:'03/28',box:'B-24',position:'2RL',status:'NOVÝ'},{id:'P-26-004',material:'Ashwagandha',lot:'14',exp:'06/28',box:'B-25',position:'Pal 4',status:'OTEVŘENÝ'}],boxes:[{id:'B-23',position:'4RL',packs:2},{id:'B-24',position:'2RL',packs:1},{id:'B-25',position:'Pal 4',packs:1}],positions:['2RL','1RP','4RL','Pal 4','Pal 6','Míchárna'],materials:['Magnesium bisglycinate','Vitamin C','Ashwagandha']};
const $=s=>document.querySelector(s);const app=$('#app');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function filtered(){const q=state.query.toLowerCase();return state.packs.filter(p=>(state.filter==='all'||p.status===state.filter)&&(!q||Object.values(p).join(' ').toLowerCase().includes(q)))}
function stats(){return `<div class="stats"><div class="stat"><b>${state.packs.length}</b><span>Packů</span></div><div class="stat"><b>${state.materials.length}</b><span>Surovin</span></div><div class="stat"><b>${state.boxes.length}</b><span>Boxů</span></div><div class="stat"><b>${state.positions.length}</b><span>Pozic</span></div></div>`}
function head(title,sub,action=''){return `<div class="page-head"><div><div class="eyebrow">BOTANIC OPERATIONS</div><h1 class="page-title">${title}</h1><div class="page-sub">${sub}</div></div>${action?`<div class="head-actions">${action}</div>`:''}</div>`}
function dashboard(){const packs=filtered();const rows=packs.map(p=>`<tr data-pack="${p.id}"><td><span class="mono">${p.id}</span><div style="color:var(--muted);font-size:11px">${esc(p.material)}</div></td><td>${esc(p.lot)}</td><td>${esc(p.exp)}</td><td><span class="mono">${p.box}</span></td><td><span class="pill pos">${esc(p.position)}</span></td><td><span class="pill"><i class="dot ${p.status==='OTEVŘENÝ'?'open':''}"></i>${p.status}</span></td></tr>`).join('');return head('Sklad','Přehled zásob a fyzického umístění',`<button class="btn" id="newBox">+ Box</button><button class="btn primary" id="newPack2">+ Pack</button>`)+stats()+`<div class="grid"><div><div class="toolbar"><button class="${state.filter==='all'?'active':''}" data-filter="all">Vše</button><button class="${state.filter==='NOVÝ'?'active':''}" data-filter="NOVÝ">Nové</button><button class="${state.filter==='OTEVŘENÝ'?'active':''}" data-filter="OTEVŘENÝ">Otevřené</button></div><div class="card"><div class="card-head"><strong>Aktuální sklad</strong><small>${packs.length} záznamů</small></div>${packs.length?`<table class="table"><thead><tr><th>Pack</th><th>Šarže</th><th>Exp.</th><th>Box</th><th>Pozice</th><th>Stav</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">Nic neodpovídá filtru.</div>'}</div></div><aside class="card"><div class="card-head"><strong>Rychlý přehled</strong></div><div class="quick"><div class="quick-item"><span>Packy</span><b>${state.packs.length}</b></div><div class="quick-item"><span>Boxy</span><b>${state.boxes.length}</b></div><div class="quick-item"><span>Pozice</span><b>${state.positions.length}</b></div></div><div class="card-head"><strong>Pozice</strong></div><div class="position-list">${state.positions.map(x=>`<button class="position" data-position="${x}"><b>${x}</b><small>${state.boxes.filter(b=>b.position===x).length} boxů</small></button>`).join('')}</div></aside></div>`}
function packs(){return head('Packy','Evidence jednotlivých balení',`<button class="btn primary" id="newPack3">+ Pack</button>`)+`<div class="card"><table class="table"><thead><tr><th>ID Pack</th><th>Surovina</th><th>Šarže</th><th>Expirace</th><th>Box</th><th>Pozice</th><th>Stav</th></tr></thead><tbody>${filtered().map(p=>`<tr data-pack="${p.id}"><td class="mono">${p.id}</td><td>${esc(p.material)}</td><td>${esc(p.lot)}</td><td>${esc(p.exp)}</td><td class="mono">${p.box}</td><td><span class="pill pos">${esc(p.position)}</span></td><td>${p.status}</td></tr>`).join('')}</tbody></table></div>`}
function boxes(){return head('Boxy','Fyzické skladové jednotky. Každý Box má právě jednu Pozici.')+`<div class="list">${state.boxes.map(b=>`<div class="list-row" data-box="${b.id}"><div class="row-main"><span class="mono">${b.id}</span><div><b>${b.position}</b><small>${b.packs} Packy</small></div></div><span>›</span></div>`).join('')}</div>`}
function positions(){return head('Pozice','Přehled fyzických umístění')+`<div class="grid"><div class="list">${state.positions.map(p=>`<div class="list-row" data-position="${p}"><div><span class="mono">${p}</span><small style="display:block;color:var(--muted)">${state.boxes.filter(b=>b.position===p).length} Boxů · ${state.packs.filter(x=>x.position===p).length} Packů</small></div><span>›</span></div>`).join('')}</div></div>`}
function materials(){return head('Suroviny','Master seznam surovin')+`<div class="list">${state.materials.map(m=>`<div class="list-row"><div><b>${esc(m)}</b><small>${state.packs.filter(p=>p.material===m).length} Packů</small></div><span>›</span></div>`).join('')}</div>`}
function moves(){return head('Pohyby','Operace přesunu a změny umístění')+`<div class="card"><div class="empty">Historie operací bude napojena na skutečný backend. UI už rozlišuje přesun Packu a přesun Boxu.</div></div>`}
function history(){return head('Historie','Audit skladových operací')+`<div class="card"><div class="empty">Připraveno pro POHYBY_LOG / audit trail.</div></div>`}
function render(){app.innerHTML=({dashboard, packs, boxes, positions, materials, moves, history}[state.view]||dashboard)();bind();}
function openDrawer(html){$('#drawerContent').innerHTML=html;$('#overlay').classList.add('open');$('#drawer').classList.add('open')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('open')}
function packDetail(id){const p=state.packs.find(x=>x.id===id);if(!p)return;openDrawer(`<div class="eyebrow">PACK</div><h2>${p.id}</h2><div class="detail-meta">${esc(p.material)}</div><div class="detail-grid"><div class="detail-row"><small>Surovina</small>${esc(p.material)}</div><div class="detail-row"><small>Šarže</small>${esc(p.lot)}</div><div class="detail-row"><small>Expirace</small>${esc(p.exp)}</div><div class="detail-row"><small>Stav</small>${p.status}</div><div class="detail-row"><small>Box</small><b class="mono">${p.box}</b></div><div class="detail-row"><small>Pozice</small><span class="pill pos">${esc(p.position)}</span></div></div><div style="margin-top:18px"><button class="btn primary" onclick="movePack('${p.id}')">Přesunout Pack</button></div>`)}
function boxDetail(id){const b=state.boxes.find(x=>x.id===id);if(!b)return;const ps=state.packs.filter(p=>p.box===id);openDrawer(`<div class="eyebrow">BOX</div><h2>${b.id}</h2><div class="detail-meta">Fyzická skladová jednotka</div><div class="detail-grid"><div class="detail-row"><small>Pozice</small><span class="pill pos">${esc(b.position)}</span></div><div class="detail-row"><small>Packy</small>${ps.length}</div></div><h3 style="margin-top:22px">Obsah</h3>${ps.map(p=>`<div class="list-row" style="margin-top:6px" data-pack="${p.id}"><div><span class="mono">${p.id}</span><small>${esc(p.material)} · ${p.status}</small></div><span>›</span></div>`).join('')}<div style="margin-top:18px"><button class="btn primary" onclick="moveBox('${b.id}')">Přesunout Box</button></div><div style="margin-top:18px;color:var(--muted);font-size:11px">Pravidlo: jeden Box = právě jedna Pozice. Přesun Boxu automaticky mění odvozenou Pozici všech Packů uvnitř.</div>`)}
function modalPack(){const options=state.boxes.map(b=>`<option value="${b.id}">${b.id} · ${b.position}</option>`).join('');$('#modalContent').innerHTML=`<h2>Nový Pack</h2><div class="field"><label>ID Packu</label><input id="fId" value="P-26-${String(state.packs.length+1).padStart(3,'0')}"></div><div class="field"><label>Surovina</label><select id="fMaterial">${state.materials.map(m=>`<option>${esc(m)}</option>`).join('')}</select></div><div class="field"><label>Šarže</label><input id="fLot"></div><div class="field"><label>Expirace MM/YY</label><input id="fExp" placeholder="01/28"></div><div class="field"><label>Box</label><select id="fBox">${options}</select></div><div class="field"><label>Stav</label><select id="fStatus"><option>NOVÝ</option><option>OTEVŘENÝ</option></select></div><div class="modal-actions"><button class="btn" id="cancelModal">Zrušit</button><button class="btn primary" id="savePack">Vytvořit Pack</button></div>`;$('#modal').classList.add('open');$('#cancelModal').onclick=closeModal;$('#savePack').onclick=()=>{const id=$('#fId').value.trim().toUpperCase();if(!/^P-\d{2}-\d+$/.test(id)||state.packs.some(p=>p.id===id))return toast('Neplatné nebo duplicitní ID Packu');const b=state.boxes.find(x=>x.id===$('#fBox').value);state.packs.push({id,material:$('#fMaterial').value,lot:$('#fLot').value,exp:$('#fExp').value,box:b.id,position:b.position,status:$('#fStatus').value});b.packs++;closeModal();render();toast('Pack vytvořen')}}
function modalBox(id){const b=state.boxes.find(x=>x.id===id);$('#modalContent').innerHTML=`<h2>Přesun Boxu ${id}</h2><div class="field"><label>Nová Pozice</label><select id="fPosition">${state.positions.map(p=>`<option ${p===b.position?'selected':''}>${p}</option>`).join('')}</select></div><div class="modal-actions"><button class="btn" id="cancelModal">Zrušit</button><button class="btn primary" id="saveMove">Přesunout Box</button></div>`;$('#modal').classList.add('open');$('#cancelModal').onclick=closeModal;$('#saveMove').onclick=()=>{b.position=$('#fPosition').value;state.packs.filter(p=>p.box===id).forEach(p=>p.position=b.position);closeModal();render();toast('Box přesunut')}}
function movePack(id){const p=state.packs.find(x=>x.id===id);$('#modalContent').innerHTML=`<h2>Přesun Packu ${id}</h2><div class="field"><label>Nový Box</label><select id="fBox">${state.boxes.map(b=>`<option ${b.id===p.box?'selected':''}>${b.id} · ${b.position}</option>`).join('')}</select></div><div class="modal-actions"><button class="btn" id="cancelModal">Zrušit</button><button class="btn primary" id="saveMove">Přesunout</button></div>`;$('#modal').classList.add('open');$('#cancelModal').onclick=closeModal;$('#saveMove').onclick=()=>{const id=$('#fBox').value.split(' · ')[0];const old=state.boxes.find(b=>b.id===p.box);const next=state.boxes.find(b=>b.id===id);if(old)old.packs--;next.packs++;p.box=next.id;p.position=next.position;closeModal();closeDrawer();render();toast('Pack přesunut')}}
function closeModal(){$('#modal').classList.remove('open')}
function bind(){document.querySelectorAll('[data-pack]').forEach(e=>e.onclick=()=>packDetail(e.dataset.pack));document.querySelectorAll('[data-box]').forEach(e=>e.onclick=()=>boxDetail(e.dataset.box));document.querySelectorAll('[data-position]').forEach(e=>e.onclick=()=>{state.query=e.dataset.position;$('#search').value=state.query;state.view='packs';render()});document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>{state.filter=e.dataset.filter;render()});$('#newPack, #newPack2, #newPack3')?.addEventListener('click',modalPack);$('#newBox')?.addEventListener('click',()=>{toast('Nový Box: vyber pozici v další iteraci')})}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>{if(!n.dataset.view)return;document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');state.view=n.dataset.view;render()}));$('#search').addEventListener('input',e=>{state.query=e.target.value;render()});$('#refresh').onclick=()=>{state.query='';$('#search').value='';render();toast('Přehled obnoven')};$('#overlay').onclick=closeDrawer;$('#drawerClose').onclick=closeDrawer;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}});render();
